version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV 
            virtualenv app
            . app/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . app/bin/activate
            python test_demo.py
      - setup_remote_docker:
          docker_layer_caching: true
      - context: DOCKER_LOGIN
      - run:
          name: Build and push Docker image
          command: |
            . app/bin/activate
            pyinstaller -F app.py
            docker build -t ariv3ra/$IMAGE_NAME:$TAG .
            echo DOCKER_LOGIN| docker login -u DOCKER_LOGIN --password-stdin
            docker push nkuriakose1/$IMAGE_NAME:$TAG