version: 2.1
jobs:
  building image:
    docker:
      - image: cimg/python:3.8.4
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV 
            virtualenv app
            . app/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . app/bin/activate
            python tests/test_demo.py
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            . app/bin/activate
            pyinstaller -F app.py
            docker build -t nkuriakose1/$IMAGE_NAME:$TAG .
            echo Docker_Login| docker login -u Docker_Login --password-stdin
            docker push nkuriakose1/$IMAGE_NAME:$TAG

workflows: 
    version: 2
    Build-Deploy: 
      jobs: 
          - building image:
              context: Docker_Login
        